#!/usr/bin/env node

/**
 * White-Label Setup Script
 *
 * Usage:
 *   node scripts/white-label.js tenant.json
 *   node scripts/white-label.js --example     # Generate example JSON
 *   node scripts/white-label.js --current     # Export current config as JSON
 *
 * This script updates:
 *   - lib/config/tenant.ts        (client-side config)
 *   - functions/src/config/tenant.ts (Cloud Functions config)
 *   - app/globals.css              (CSS variables)
 *
 * After running, you still need to:
 *   1. Replace logo/icon files in /public/
 *   2. Set up Firebase project + env vars
 *   3. Deploy (git push)
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');

// ---------- Example / current export ----------

const EXAMPLE = {
  appName: 'Acme Pro',
  shortName: 'Acme',
  tagline: 'Professional Business Management',
  description: 'Unified business management for Acme companies',
  copyright: 'Acme Pro',
  logoPath: '/logo.png',
  logoIconPath: '/logo.svg',
  logoIconText: 'AP',
  faviconPath: '/favicon.ico',
  supportEmail: 'support@acmepro.com',
  billingEmail: 'billing@acmepro.com',
  noreplyEmail: 'noreply@acmepro.com',
  phone: '5551234567',
  domain: 'acmepro.com',
  serviceArea: 'Dallas-Fort Worth Metro Area',
  adminEmails: ['admin@acmepro.com'],
  firebaseProjectId: 'acme-pro-12345',
  entities: {
    kd: { label: 'Acme Digital', shortLabel: 'AD' },
    kts: { label: 'Acme Trade Services', shortLabel: 'ATS' },
    kr: { label: 'Acme Renovations', shortLabel: 'AR' },
  },
  commissionRates: { elite: 0.1, pro: 0.09, standard: 0.08 },
  ratingThresholds: { elite: 4.5, pro: 3.5, standard: 2.5, needsImprovement: 1.5 },
  subscriptionTiers: {
    starter: { monthlyFee: 399, leadRange: '10-15', adSpendMin: 600 },
    growth: { monthlyFee: 899, leadRange: '15-25', adSpendMin: 900 },
    pro: { monthlyFee: 1499, leadRange: 'Flexible', adSpendMin: 1500 },
  },
  colors: {
    primary: '#3B82F6',
    primaryLight: '#60A5FA',
    primaryDark: '#2563EB',
    background: '#0F172A',
    surface: '#1E293B',
  },
};

// ---------- Helpers ----------

function die(msg) {
  console.error(`\x1b[31mError:\x1b[0m ${msg}`);
  process.exit(1);
}

function ok(msg) {
  console.log(`\x1b[32m✓\x1b[0m ${msg}`);
}

function validate(cfg) {
  const required = [
    'appName', 'shortName', 'tagline', 'description', 'copyright',
    'supportEmail', 'billingEmail', 'noreplyEmail', 'phone', 'domain',
    'serviceArea', 'adminEmails', 'firebaseProjectId',
    'entities', 'commissionRates', 'ratingThresholds', 'subscriptionTiers', 'colors',
  ];

  for (const key of required) {
    if (cfg[key] === undefined) die(`Missing required field: "${key}"`);
  }

  for (const entity of ['kd', 'kts', 'kr']) {
    if (!cfg.entities[entity]?.label || !cfg.entities[entity]?.shortLabel) {
      die(`entities.${entity} must have "label" and "shortLabel"`);
    }
  }

  for (const color of ['primary', 'primaryLight', 'primaryDark', 'background', 'surface']) {
    if (!cfg.colors[color]?.match(/^#[0-9A-Fa-f]{6}$/)) {
      die(`colors.${color} must be a 6-digit hex color (e.g. "#3B82F6"), got "${cfg.colors[color]}"`);
    }
  }

  if (!Array.isArray(cfg.adminEmails) || cfg.adminEmails.length === 0) {
    die('adminEmails must be a non-empty array');
  }
}

// ---------- File generators ----------

function generateClientTenant(cfg) {
  return `// Tenant configuration — centralized brand, entity, and business constants.
// To white-label: change values here. All UI, PDFs, emails, and logic read from this file.
// AUTO-GENERATED by scripts/white-label.js — do not edit manually.

export type EntityKey = 'kd' | 'kts' | 'kr';

export interface EntityConfig {
  label: string;
  shortLabel: string;
}

export interface TenantConfig {
  // Brand
  appName: string;
  shortName: string;
  tagline: string;
  description: string;
  copyright: string;
  logoPath: string;
  logoIconPath: string;
  logoIconText: string;
  faviconPath: string;

  // Contact
  supportEmail: string;
  billingEmail: string;
  noreplyEmail: string;
  phone: string;
  domain: string;

  // Service area
  serviceArea: string;

  // Admin notification emails
  adminEmails: string[];

  // Firebase project
  firebaseProjectId: string;

  // Business entities (the three sub-brands)
  entities: Record<EntityKey, EntityConfig>;

  // Commission rates by rating tier
  commissionRates: {
    elite: number;
    pro: number;
    standard: number;
  };

  // Rating tier thresholds (minimum overall rating for each tier)
  ratingThresholds: {
    elite: number;
    pro: number;
    standard: number;
    needsImprovement: number;
  };

  // Subscription tiers (KD module)
  subscriptionTiers: {
    starter: { monthlyFee: number; leadRange: string; adSpendMin: number };
    growth: { monthlyFee: number; leadRange: string; adSpendMin: number };
    pro: { monthlyFee: number; leadRange: string; adSpendMin: number };
  };

  // Colors (used in emails, PDFs, and inline styles — Tailwind colors are in tailwind.config.ts)
  colors: {
    primary: string;
    primaryLight: string;
    primaryDark: string;
    background: string;
    surface: string;
  };
}

export const tenant: TenantConfig = {
  // Brand
  appName: ${JSON.stringify(cfg.appName)},
  shortName: ${JSON.stringify(cfg.shortName)},
  tagline: ${JSON.stringify(cfg.tagline)},
  description: ${JSON.stringify(cfg.description)},
  copyright: ${JSON.stringify(cfg.copyright)},
  logoPath: ${JSON.stringify(cfg.logoPath || '/logo.png')},
  logoIconPath: ${JSON.stringify(cfg.logoIconPath || '/logo.svg')},
  logoIconText: ${JSON.stringify(cfg.logoIconText || cfg.shortName.substring(0, 2).toUpperCase())},
  faviconPath: ${JSON.stringify(cfg.faviconPath || '/favicon.ico')},

  // Contact
  supportEmail: ${JSON.stringify(cfg.supportEmail)},
  billingEmail: ${JSON.stringify(cfg.billingEmail)},
  noreplyEmail: ${JSON.stringify(cfg.noreplyEmail)},
  phone: ${JSON.stringify(cfg.phone)},
  domain: ${JSON.stringify(cfg.domain)},

  // Service area
  serviceArea: ${JSON.stringify(cfg.serviceArea)},

  // Admin notification emails
  adminEmails: ${JSON.stringify(cfg.adminEmails)},

  // Firebase project
  firebaseProjectId: ${JSON.stringify(cfg.firebaseProjectId)},

  // Business entities
  entities: {
    kd: { label: ${JSON.stringify(cfg.entities.kd.label)}, shortLabel: ${JSON.stringify(cfg.entities.kd.shortLabel)} },
    kts: { label: ${JSON.stringify(cfg.entities.kts.label)}, shortLabel: ${JSON.stringify(cfg.entities.kts.shortLabel)} },
    kr: { label: ${JSON.stringify(cfg.entities.kr.label)}, shortLabel: ${JSON.stringify(cfg.entities.kr.shortLabel)} },
  },

  // Commission rates
  commissionRates: {
    elite: ${cfg.commissionRates.elite},
    pro: ${cfg.commissionRates.pro},
    standard: ${cfg.commissionRates.standard},
  },

  // Rating thresholds
  ratingThresholds: {
    elite: ${cfg.ratingThresholds.elite},
    pro: ${cfg.ratingThresholds.pro},
    standard: ${cfg.ratingThresholds.standard},
    needsImprovement: ${cfg.ratingThresholds.needsImprovement},
  },

  // Subscription tiers
  subscriptionTiers: {
    starter: { monthlyFee: ${cfg.subscriptionTiers.starter.monthlyFee}, leadRange: ${JSON.stringify(cfg.subscriptionTiers.starter.leadRange)}, adSpendMin: ${cfg.subscriptionTiers.starter.adSpendMin} },
    growth: { monthlyFee: ${cfg.subscriptionTiers.growth.monthlyFee}, leadRange: ${JSON.stringify(cfg.subscriptionTiers.growth.leadRange)}, adSpendMin: ${cfg.subscriptionTiers.growth.adSpendMin} },
    pro: { monthlyFee: ${cfg.subscriptionTiers.pro.monthlyFee}, leadRange: ${JSON.stringify(cfg.subscriptionTiers.pro.leadRange)}, adSpendMin: ${cfg.subscriptionTiers.pro.adSpendMin} },
  },

  // Colors (for inline styles, emails, PDFs — not Tailwind classes)
  colors: {
    primary: ${JSON.stringify(cfg.colors.primary)},
    primaryLight: ${JSON.stringify(cfg.colors.primaryLight)},
    primaryDark: ${JSON.stringify(cfg.colors.primaryDark)},
    background: ${JSON.stringify(cfg.colors.background)},
    surface: ${JSON.stringify(cfg.colors.surface)},
  },
};

// Convenience helpers
export function getEntityLabel(key: EntityKey): string {
  return tenant.entities[key].label;
}

export function getEntityShortLabel(key: EntityKey): string {
  return tenant.entities[key].shortLabel;
}

export function getEntityFullName(key: string): string {
  if (key in tenant.entities) return tenant.entities[key as EntityKey].label;
  if (key === 'customer') return 'Customers';
  if (key === 'subscriber') return 'Subscribers';
  if (key === 'contractor') return 'Contractor';
  return key;
}

export function formatCommissionLabel(tier: 'elite' | 'pro' | 'standard'): string {
  const rate = tenant.commissionRates[tier];
  const pct = Math.round(rate * 100);
  const name = tier.charAt(0).toUpperCase() + tier.slice(1);
  return \`\${name} (\${pct}%)\`;
}
`;
}

function generateFunctionsTenant(cfg) {
  return `// Tenant configuration for Cloud Functions
// Mirrors lib/config/tenant.ts — to white-label, change values here and in the client config.
// AUTO-GENERATED by scripts/white-label.js — do not edit manually.

export type EntityKey = 'kd' | 'kts' | 'kr';

export interface EntityConfig {
  label: string;
  shortLabel: string;
}

export const tenant = {
  // Brand
  appName: ${JSON.stringify(cfg.appName)},
  shortName: ${JSON.stringify(cfg.shortName)},
  tagline: ${JSON.stringify(cfg.tagline)},
  description: ${JSON.stringify(cfg.description)},

  // Contact
  supportEmail: ${JSON.stringify(cfg.supportEmail)},
  noreplyEmail: ${JSON.stringify(cfg.noreplyEmail)},
  domain: ${JSON.stringify(cfg.domain)},

  // Service area
  serviceArea: ${JSON.stringify(cfg.serviceArea)},

  // Admin notification emails
  adminEmails: ${JSON.stringify(cfg.adminEmails)},

  // Firebase project
  firebaseProjectId: ${JSON.stringify(cfg.firebaseProjectId)},

  // Business entities
  entities: {
    kd: { label: ${JSON.stringify(cfg.entities.kd.label)}, shortLabel: ${JSON.stringify(cfg.entities.kd.shortLabel)} },
    kts: { label: ${JSON.stringify(cfg.entities.kts.label)}, shortLabel: ${JSON.stringify(cfg.entities.kts.shortLabel)} },
    kr: { label: ${JSON.stringify(cfg.entities.kr.label)}, shortLabel: ${JSON.stringify(cfg.entities.kr.shortLabel)} },
  } as Record<EntityKey, EntityConfig>,

  // Colors (for inline styles in emails)
  colors: {
    primary: ${JSON.stringify(cfg.colors.primary)},
    primaryLight: ${JSON.stringify(cfg.colors.primaryLight)},
    primaryDark: ${JSON.stringify(cfg.colors.primaryDark)},
    background: ${JSON.stringify(cfg.colors.background)},
    surface: ${JSON.stringify(cfg.colors.surface)},
  },
} as const;

// Convenience helpers
export function getEntityLabel(key: EntityKey): string {
  return tenant.entities[key].label;
}

export function getEntityFullName(entity: string): string {
  if (entity in tenant.entities) return tenant.entities[entity as EntityKey].label;
  if (entity === 'customer') return 'Customers';
  if (entity === 'subscriber') return 'Subscribers';
  if (entity === 'contractor') return 'Contractor';
  return entity;
}
`;
}

function updateGlobalsCss(cfg) {
  const cssPath = path.join(ROOT, 'app', 'globals.css');
  let css = fs.readFileSync(cssPath, 'utf-8');

  // Replace the CSS variables block
  css = css.replace(
    /:root\s*\{[^}]*\}/,
    `:root {
  --brand-gold: ${cfg.colors.primary};
  --brand-gold-light: ${cfg.colors.primaryLight};
  --brand-gold-dark: ${cfg.colors.primaryDark};
  --brand-black: ${cfg.colors.background};
  --brand-charcoal: ${cfg.colors.surface};
}`
  );

  fs.writeFileSync(cssPath, css, 'utf-8');
}

// ---------- Main ----------

const args = process.argv.slice(2);

if (args.includes('--help') || args.length === 0) {
  console.log(`
\x1b[1mWhite-Label Setup Script\x1b[0m

Usage:
  node scripts/white-label.js <tenant.json>   Apply tenant config
  node scripts/white-label.js --example       Generate example tenant.json
  node scripts/white-label.js --current       Export current config as JSON

After running, remember to:
  1. Replace logo/icon files in /public/
  2. Set up Firebase project + environment variables
  3. Deploy (git push)
`);
  process.exit(0);
}

if (args.includes('--example')) {
  const outPath = path.join(ROOT, 'tenant-example.json');
  fs.writeFileSync(outPath, JSON.stringify(EXAMPLE, null, 2) + '\n', 'utf-8');
  ok(`Example config written to ${outPath}`);
  console.log('\nEdit it with your client\'s info, then run:');
  console.log('  node scripts/white-label.js tenant-example.json\n');
  process.exit(0);
}

if (args.includes('--current')) {
  // Read current tenant.ts and extract the config values
  const tenantPath = path.join(ROOT, 'lib', 'config', 'tenant.ts');
  // Quick and dirty: require it by evaluating... or just tell user to copy
  console.log('Current tenant config values (copy from lib/config/tenant.ts):');
  const tenantSrc = fs.readFileSync(tenantPath, 'utf-8');
  // Extract the object between "tenant: TenantConfig = {" and the closing "};"
  const match = tenantSrc.match(/export const tenant: TenantConfig = (\{[\s\S]*?\n\};)/);
  if (match) {
    // Convert TS object to JSON-ish output
    let obj = match[1]
      .replace(/\/\/.*/g, '')           // strip comments
      .replace(/,(\s*[}\]])/g, '$1')    // strip trailing commas
      .replace(/(\w+):/g, '"$1":')      // quote keys
      .replace(/'/g, '"');              // single to double quotes
    try {
      const parsed = JSON.parse(obj.replace(/;\s*$/, ''));
      console.log(JSON.stringify(parsed, null, 2));
    } catch {
      console.log('\nCould not auto-parse. Here are the raw values:\n');
      console.log(obj);
    }
  }
  process.exit(0);
}

// Apply tenant config
const jsonPath = path.resolve(args[0]);
if (!fs.existsSync(jsonPath)) {
  die(`File not found: ${jsonPath}`);
}

let cfg;
try {
  cfg = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
} catch (e) {
  die(`Invalid JSON: ${e.message}`);
}

validate(cfg);

console.log(`\n\x1b[1mApplying white-label config for: ${cfg.appName}\x1b[0m\n`);

// Write client tenant config
const clientPath = path.join(ROOT, 'lib', 'config', 'tenant.ts');
fs.writeFileSync(clientPath, generateClientTenant(cfg), 'utf-8');
ok(`Updated ${path.relative(ROOT, clientPath)}`);

// Write functions tenant config
const functionsPath = path.join(ROOT, 'functions', 'src', 'config', 'tenant.ts');
fs.writeFileSync(functionsPath, generateFunctionsTenant(cfg), 'utf-8');
ok(`Updated ${path.relative(ROOT, functionsPath)}`);

// Update CSS variables
updateGlobalsCss(cfg);
ok('Updated app/globals.css CSS variables');

console.log(`
\x1b[1m\x1b[32mDone!\x1b[0m Config updated for \x1b[1m${cfg.appName}\x1b[0m.

\x1b[1mRemaining steps:\x1b[0m
  1. Replace logo files in /public/ (logo.png, logo.svg, favicon.ico, icons/*)
  2. Set up Firebase project (${cfg.firebaseProjectId}) + env vars in .env.local
  3. Build functions:  cd functions && npm run build
  4. Deploy:           git push
`);
